name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PUBLIC_PAT: ${{ secrets.PUBLIC_PAT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - run: npm install

      - run: npm run build

      - run: npm run lint
